- name: Fail if "datadog_key" is undefined
  ansible.builtin.fail:
    msg: "Unable to install datadog - datadog_key is missing"
  when: datadog_key is undefined

- name: Install Datadog
  ansible.builtin.include_role:
    name: datadog.datadog
  vars:
    datadog_api_key: "{{ datadog_key }}"
    datadog_site: "datadoghq.eu"
