- hosts: all
  name: Install docker
  become: true
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - role: docker
    - role: geerlingguy.pip

- hosts: webservers
  name: Deploy redmine and Datadog
  become: true
  roles:
    - role: redmine
    - role: datadog
