- hosts: all
  name: Install docker
  become: true
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - role: docker
    - role: geerlingguy.pip

- hosts: webservers
  name: Deploy redmine and Datadog
  become: true
  roles:
    - role: redmine
    - role: datadog
  vars:
    datadog_checks:
      http:
        init_config:
        instances:
          - name: from-external
            url: "https://{{ domain_name }}"
          - name: internal
            url: http://127.0.0.1
