- hosts: all
  name: Deploy project
  become: true
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - role: docker
    - role: geerlingguy.pip

- hosts: webservers
  name: Deploy redmine
  become: true
  roles:
    - role: redmine
