- name: Gather package facts
  ansible.builtin.package_facts:
    manager: apt

- name: Docker package status
  ansible.builtin.debug:
    msg: 'Docker-ce has been already installed'
  when: '"docker-ce" in ansible_facts.packages'

- name: Install docker
  ansible.builtin.include_tasks: install-docker.yml
  when: '"docker-ce" not in ansible_facts.packages'
